name: DoZor
description: Приложение для проверки качества масел по фотографии

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.0+1
  photo_view: ^0.14.0
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.0.11
  ml_algo: ^16.17.3
  ml_dataframe: ^1.6.0
  image_picker: ^0.8.6
  test: ^1.21.4
  tuple: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.1.7
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "img/launcher_icons/1024.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
    - family: Gotham Pro
      fonts:
        # - asset: fonts/GothamPro/GothamPro-Black.ttf
        #   weight: 900
        - asset: fonts/GothamPro/GothamPro-Bold.ttf
          weight: 700
        - asset: fonts/GothamPro/GothamPro-Medium.ttf
          weight: 500
        - asset: fonts/GothamPro/GothamPro.ttf
          weight: 400
        - asset: fonts/GothamPro/GothamPro-Light.ttf
          weight: 300

flutter_intl:
  main_locale: ru
  enabled: true