name: DoZor
description: Приложение для проверки качества масел по фотографии

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.0+1
  photo_view: ^0.14.0
  google_fonts: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.0.11
  ml_algo: ^16.17.3
  ml_dataframe: ^1.6.0
  image_picker: ^0.8.6
  test: ^1.21.4
  tuple: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_speed_dial: ^6.1.0+1
  flutter_simple_dependency_injection: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "img/launcher_icons/1024.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - data/new_samples/
    - img/

flutter_intl:
  main_locale: ru
  enabled: true